sudo: false
language: node_js
cache:
  npm: true
  directories:
    - node_modules
node_js:
- '8'
script:
- npm run check
after_success:
# Deploy code coverage report to codecov.io
- npm run test:coverage:deploy
